
language: java
install: true
jdk:
    - openjdk8
env:
  matrix:
  - TERM=dumb
before_script:
  - ./gradlew --version
script: ./gradlew build
after_success:
  - ./gradlew jacocoTestReport coveralls
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
