= Gradle HTTP Plugin User Guide
Christopher J. Stehno <chris@stehno.com>
v0.0.1, October 2017
:toc: left
:toclevels: 4

== Introduction

The Gradle HTTP Plugin provides a straight-forward means of configuring and executing HTTP requests from your Gradle build, using the
https://http-builder-ng.github.io/http-builder-ng[HttpBuilder-NG] client library.

== Getting Started

In order to use the HTTP Plugin to create HTTP tasks, you first need to apply it to your build. The plugin is available via the common Gradle plugins
repository as https://plugins.gradle.org/plugin/io.github.http-builder-ng.http-plugin[io.github.http-builder-ng.http-plugin]. You can then apply it
to your build with by adding the following to your `build.gradle` file:

[source,groovy]
.build.gradle
----
plugins {
  id "io.github.http-builder-ng.http-plugin" version "0.0.1"
}
----

Next, you will need to create a task of type `io.github.httpbuilderng.http.HttpTask` to preform your requests. The following is an example:

[source,groovy]
.build.gradle
----
task notify(type:HttpTask){
    config {
        request.uri = 'http://something.com'
    }
    post {
        request.uri.path = '/notify'
        request.body = [event: 'activated']
        response.success {
            println 'The event notification was successful'
        }
    }
}
----

This `notify` task will send a POST request to http://something.com/notify with the given payload whenever the task is executed.

== Configuration

=== `http` Extension

> TBD: global configuration and library specification

=== `HttpTask`

> TBD: request methods, not about missing methods and multiple requests (async)

== License

The Gradle HTTP Plugin is licensed under the http://www.apache.org/licenses/LICENSE-2.0[Apache 2] open source license.

    Copyright 2017 HttpBuilder-NG Project

    Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
